### ISSUE TITLE
How should I use these scripts?

### ISSUE THREAD

**Issue by geng-lee** [maxwshen/lib-dataprocessing#1]
Dear Dr. Shen,

How should I use these scripts? Can you provide a description of the execution process for running these scripts (eg. The order that the scripts are executed), including the type , data structure of input file, and interpretation of the output file? Thanks!

Best Wishes,
Geng

**Comment by maxwshen** [comment]
Hi, these scripts are provided primarily as an archive of the code used to process the data, and accompany the methods sections while providing more detail. They are not convenient to run, as we anticipated that very few groups would have interest in rerunning our code. Our processed data is available in the figshare links in the manuscript which is sufficient to retrain the machine learning models. If you have more specific questions on what you are interested in, I may be able to help further. If you would like to reproduce the data processing code, I would suggest the high level strategy of outlining the process from our methods sections, and then referencing the code to obtain exact details when necessary. It should be possible to rerun the pipeline using the code provided here, but it will likely need code editing and adjustments to your environment.
